CREATE TABLE "C##HIMEDIA"."ZOOLOGIN" 
   (	"ZL_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ZL_PW" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ZOOLOGIN" PRIMARY KEY ("ZL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "C##HIMEDIA"."PK_ZOOLOGIN" ON "C##HIMEDIA"."ZOOLOGIN" ("ZL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;